### ISSUE TITLE
feature/Rc-Racer

### ISSUE THREAD

**Issue by matk92** [NicoCalvelo/DisneylandESGI#13]
C'est l'heure d'une nouveauté à Disneyland ESGI ! Nous avons besoin d'un développeur pour le faire vivre !

Nous avons besoin de Rc-Racer qui apporte du divertissement au apporterait du divertissement au parc.

Toutes les contributions supplémentaires seront les bienvenues à condition qu'elles soient bien testées et exemptes de défauts de fonctionnement.

**Comment by RemySaguez** [comment]
new feature
